// AUTO-GENERATED from Sara's Trading Post eBay storefront. Edit the generator, not this file.
export type Category = "Makeup" | "Skincare" | "Fragrance";

export interface Product {
  id: string;
  title: string;
  brand: string;
  category: Category;
  sub: string;
  price: number;
  compareAt: number;
  image: string;
  rating: number;
  reviews: number;
  sold: number;
  condition: string;
  blurb: string;
  bestseller: boolean;
  description?: string;
  variation?: { label: string; options: string[] };
}

export const products: Product[] = [
  {
    "id": "lyuaaoswqa5jpz3q",
    "title": "DISCONTINUED Estee Lauder ORIGINAL Double Wear Makeup Foundation 1oz/30ml",
    "brand": "Estee Lauder",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 37.01,
    "compareAt": 52.39,
    "image": "https://i.ebayimg.com/images/g/lyUAAOSwQA5jPZ3Q/s-l800.jpg",
    "rating": 4.7,
    "reviews": 59,
    "sold": 99,
    "condition": "Rare / Discontinued",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Estée Lauder Double Wear Stay-in-Place Makeup is the foundation that defined long-wear — 24 hours of waterproof, transfer-resistant coverage with a natural matte finish and no touch-ups required. Buildable from medium to full coverage, it evens skin tone, stays color true all day, and resists sweat and humidity. Oil-free, non-acnegenic, SPF 10. The beloved original formula, now discontinued and increasingly hard to find. Full regular size, 1 oz / 30 ml, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene. Pick your shade from the menu.",
    "variation": {
      "label": "Shade",
      "options": [
        "0N1 Alabaster",
        "1C0 Shell",
        "1C1 Cool Bone",
        "1N0 Porcelain",
        "1N1 Ivory Nude",
        "1N2 Ecru",
        "1W0 Warm Porcelain",
        "1W1 Bone",
        "1W2 Sand",
        "2C0 Cool Vanilla",
        "2C1 Pure Beige",
        "2C3 Fresco",
        "2C4 Ivory Rose",
        "2N1 Desert Beige",
        "2N2 Buff",
        "2W0 Warm Vanilla",
        "2W1 Dawn",
        "2W2 Rattan",
        "3C1 Dusk",
        "3C2 Pebble",
        "3C3 Sandbar",
        "3N1 Ivory Beige",
        "3N2 Wheat",
        "3W1 Tawny",
        "3W1.5 Fawn",
        "3W2 Cashew",
        "4C1 Outdoor Beige",
        "4C2 Auburn",
        "4C3 Softan Soft Tan",
        "4N1 Shell Beige",
        "4N2 Spiced Sand",
        "4N3 Maple Sugar",
        "4W1 Honey Bronze",
        "4W2 Toasty Toffee",
        "4W3 Henna",
        "4W4 Hazel",
        "5C1 Rich Chestnut",
        "5C2 Sepia",
        "5N1 Rich Ginger",
        "5N1.5 Maple",
        "5N2 Amber Honey",
        "5W1 Bronze",
        "5W1.5 Cinnamon",
        "5W2 Rich Caramel",
        "6C1 Rich Cocoa",
        "6C2 Pecan",
        "6N1 Mocha",
        "6N2 Truffle",
        "6W1 Sandalwood",
        "6W2 Nutmeg",
        "7C1 Rich Mahogany",
        "7C2 Sienna",
        "7N1 Deep Amber",
        "7W1 Deep Spice",
        "8C1 Rich Java",
        "8N1 Espresso"
      ]
    }
  },
  {
    "id": "eeqaaeswksxoydt",
    "title": "YSL Yves Saint Laurent Rouge Pur Couture SATINY RADIANCE LIPSTICK .13oz/3.8g",
    "brand": "YSL",
    "category": "Makeup",
    "sub": "Lips",
    "price": 31.95,
    "compareAt": 41.07,
    "image": "https://i.ebayimg.com/images/g/EEQAAeSwkSxoyd~t/s-l800.jpg",
    "rating": 4.6,
    "reviews": 19,
    "sold": 175,
    "condition": "New (Sealed)",
    "blurb": "Long-wear color with a luxurious, comfortable finish.",
    "bestseller": false,
    "description": "YSL Rouge Pur Couture lipstick in three limited-edition Satiny Radiance shades — a luxuriously pigmented formula that lays on vivid color in a single stroke while delivering cushiony hydration and antioxidant care. The satiny finish is comfortable all day with true-to-pan color payoff. Full size, 0.13 oz / 3.8 g, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Pick your shade from the menu (each sold individually).",
    "variation": {
      "label": "Shade",
      "options": [
        "151 Unapologetic",
        "152 Rouge Extreme",
        "155 Nu Imprevu"
      ]
    }
  },
  {
    "id": "mcoaaeswyvpovivg",
    "title": "BareMinerals Original Mineral Veil Pressed Setting Powder 9g/0.3oz",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 14.95,
    "compareAt": 23.46,
    "image": "https://i.ebayimg.com/images/g/McoAAeSwYvpovIVg/s-l800.jpg",
    "rating": 4.9,
    "reviews": 107,
    "sold": 258,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "The original classic formula of bareMinerals' cult-favorite Mineral Veil. This weightless pressed setting powder locks in your makeup and extends wear while blurring the look of pores, fine lines and shine — leaving a smooth, flawless matte finish with no flashback in photos. Infused with Vitamin E to help defend against environmental stressors, and perfect for on-the-go touch-ups. Full regular size, 0.3 oz / 9 g. 100% authentic, new in box and sealed, hand-inspected and sanitized before it ships. Pick your shade from the menu — and remember to know your shade before ordering, as these are sealed for hygiene.",
    "variation": {
      "label": "Shade",
      "options": [
        "Translucent",
        "Sheer Fair",
        "Sheer Light",
        "Sheer Medium",
        "Sheer Tan"
      ]
    }
  },
  {
    "id": "x8aaeswcslo6fov",
    "title": "Tom Ford TF CREAM COLOR For EYES .17oz/5ml * RARE *",
    "brand": "Tom Ford",
    "category": "Makeup",
    "sub": "Eyes",
    "price": 90.2,
    "compareAt": 116.1,
    "image": "https://i.ebayimg.com/images/g/~x8AAeSwCSlo6FOV/s-l800.jpg",
    "rating": 4.6,
    "reviews": 19,
    "sold": 76,
    "condition": "New (Sealed)",
    "blurb": "Richly pigmented shades that blend like a dream.",
    "bestseller": false,
    "description": "Tom Ford's cult Cream Color for Eyes delivers intense, long-wearing color in a cushiony cream-to-powder formula that glides on and sets crease-resistant. Sweep it on with a fingertip for a sheer wash of light, or build it up for full metallic impact. A rare, discontinued treasure — new in box and sealed, full size 0.17 fl oz / 5 ml. 100% authentic, hand-inspected and sanitized before it ships, from a smoke-free studio. Pick your color from the menu (each is sold individually).",
    "variation": {
      "label": "Color",
      "options": [
        "02 Opale",
        "03 Sphinx"
      ]
    }
  },
  {
    "id": "bngaaesw2hpovnkz",
    "title": "IMAGE Post Injectable Skincare System Set 5 Pcs: Cleaner+Serum+Moisturizer",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Serums & Treatments",
    "price": 89.95,
    "compareAt": 117.63,
    "image": "https://i.ebayimg.com/images/g/bngAAeSw2hpovNKZ/s-l800.jpg",
    "rating": 4.7,
    "reviews": 25,
    "sold": 41,
    "condition": "New (Sealed)",
    "blurb": "Targeted actives that visibly transform skin.",
    "bestseller": false,
    "description": "IMAGE Skincare Post-Injectable Recovery System — a curated five-piece kit designed to support skin through the healing process after injectable treatments. Includes BIOME+ Cleansing Comfort Balm (50 ml), BIOME+ Dew Bright Serum (15 ml), IMAGE MD Restoring Collagen Recovery Eye Gel (15 ml), VITAL C Hydrating Repair Cream (28 g), and DAILY PREVENTION Pure Mineral Hydrating Moisturizer SPF 30 (73 g). New and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "st8aaoswhgllkiac",
    "title": "CHANEL Les Beiges Belle Mine Poudre Healthy Glow ILLUMINATING POWDER Full Size",
    "brand": "CHANEL",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 63.95,
    "compareAt": 104.84,
    "image": "https://i.ebayimg.com/images/g/st8AAOSwHgllKIac/s-l800.jpg",
    "rating": 4.9,
    "reviews": 129,
    "sold": 348,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": true,
    "description": "CHANEL Les Beiges Belle Mine Poudre illuminating powder gives skin a healthy, sun-kissed radiance in one effortless sweep. The finely milled formula diffuses light naturally for a glowing, never-powdery complexion. The full-size compact includes a large mirror and a half-moon applicator brush — perfect for at-home use or on-the-go touch-ups. Full size, 0.35 oz / 10 g, new in box. 100% authentic, hand-inspected and sanitized before it ships. Pick your shade from the menu.",
    "variation": {
      "label": "Shade",
      "options": [
        "Sand",
        "Sunset"
      ]
    }
  },
  {
    "id": "5owaaeswrtfptoqs",
    "title": "Nakery Beauty -Rapid Lift- Multi Peptide Serum- Tighten & Firm- 1.69 fl oz/50 mL",
    "brand": "Nakery Beauty",
    "category": "Skincare",
    "sub": "Serums & Treatments",
    "price": 13.95,
    "compareAt": 21.4,
    "image": "https://i.ebayimg.com/images/g/5owAAeSwrtFptOQs/s-l800.jpg",
    "rating": 4.9,
    "reviews": 96,
    "sold": 387,
    "condition": "New (Sealed)",
    "blurb": "Targeted actives that visibly transform skin.",
    "bestseller": false,
    "description": "Nakery Beauty Rapid-Lift Multi Peptide Serum is a clinically proven instant-tightening treatment that lifts and firms skin for a visibly younger, more sculpted look in seconds. The multi-peptide formula targets facial sagging, droopy eyelids, depleted cheekbones and jowls while smoothing eyelid creases, fading dark circles, eliminating under-eye puffiness and reducing crow's feet over time. It also helps build collagen and support skin cell regeneration for longer-term improvement. Full size, 1.69 fl oz / 50 ml, new and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "9f8aaeswwprptn0k",
    "title": "Nakery Beauty Skip the Line Advanced Instant Wrinkle Eraser Tighten + Smooth",
    "brand": "Nakery Beauty",
    "category": "Skincare",
    "sub": "Serums & Treatments",
    "price": 11.35,
    "compareAt": 11.95,
    "image": "https://i.ebayimg.com/images/g/9f8AAeSwwPRptN0k/s-l800.jpg",
    "rating": 4.8,
    "reviews": 73,
    "sold": 144,
    "condition": "New (Sealed)",
    "blurb": "Targeted actives that visibly transform skin.",
    "bestseller": false,
    "description": "Nakery Beauty Skip the Line Advanced Instant Wrinkle Eraser is a clinically proven wrinkle filler and line-smoother that firms and tightens skin within 3 minutes and lasts over 12 hours. The targeted formula addresses expression lines three ways: immediately smoothing the skin's surface, softening the look of deep-set wrinkles over time, and minimizing future lines and pores. Key actives include Argireline (a peptide muscle relaxer), hydrolyzed hyaluronic acid, Dolcevia, plant-based collagen and a hydrolyzed 7-complex. Blends invisibly into all skin tones with no white cast — no tapping or tools needed. Full size, 1.01 oz / 30 ml, new and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "tleaaeswpa9ptnky",
    "title": "Gucci Crayon Definition Powder Eyebrow Pencil 01 TAUPE & Sharpener .04oz",
    "brand": "Gucci",
    "category": "Makeup",
    "sub": "Eyes",
    "price": 21.95,
    "compareAt": 33.33,
    "image": "https://i.ebayimg.com/images/g/tlEAAeSwPa9ptNkY/s-l800.jpg",
    "rating": 4.8,
    "reviews": 91,
    "sold": 333,
    "condition": "New (Sealed)",
    "blurb": "Richly pigmented shades that blend like a dream.",
    "bestseller": false,
    "description": "Gucci Crayon Définition Sourcils in 01 Taupe — a powder-texture brow pencil that delivers light, buildable matte color for filling and defining brows with precision. The blendable formula mimics the look of real hair for a naturally defined finish, and once set it doesn't smudge, bleed, transfer or migrate all day. The dual-sided design pairs the pencil with a spoolie brush at the opposite end for combing color through and polishing brows into place. Housed in a pale pink casing with gold trim and the iconic Gucci logo. Kit includes pencil and sharpener, 1.19 g, new in box. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "bluaaesws3xptm5a",
    "title": "IT Cosmetics Bye Bye Under Eye Bags Rapid Bag Reducer 0.5oz/15ml x 2",
    "brand": "IT Cosmetics",
    "category": "Skincare",
    "sub": "Eye Care",
    "price": 11.95,
    "compareAt": 15.65,
    "image": "https://i.ebayimg.com/images/g/bLUAAeSws3xptM5A/s-l800.jpg",
    "rating": 4.7,
    "reviews": 26,
    "sold": 94,
    "condition": "New (Sealed)",
    "blurb": "Depuffs, firms, and brightens the delicate eye area.",
    "bestseller": false,
    "description": "IT Cosmetics Bye Bye Under Eye Bags Rapid Bag Reducer is a targeted eye treatment formulated to visibly reduce the appearance of under-eye bags, puffiness and dark circles. The concentrated formula works quickly to smooth and de-puff the delicate under-eye area for a more rested, refreshed look. Full size, 0.5 oz / 15 ml — sold as a set of 2. New and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "ogcaaeswgjxptmrt",
    "title": "Set ISDIN ISDINCEUTICS Flavo C Ultraglican Antioxidant 10 Ampoules x 2ml each",
    "brand": "ISDIN",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 28.95,
    "compareAt": 47.51,
    "image": "https://i.ebayimg.com/images/g/OGcAAeSwGjxptMrt/s-l800.jpg",
    "rating": 4.9,
    "reviews": 129,
    "sold": 103,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": true,
    "description": "ISDIN Isdinceutics Flavo-C Ultraglican is a supercharged antioxidant serum formulated with vitamin C, UltraGlycans and hyaluronic acid to protect against oxidative stress, deeply hydrate skin and visibly soften fine lines and wrinkles. The concentrated ampoule format ensures maximum freshness and potency with each use, delivering a natural, radiant glow. Paraben-free, non-comedogenic and mineral oil-free; suitable for all skin types including dehydrated, sun-damaged and those with loss of firmness. Set of 10 single-use ampoules, 2 ml each (20 ml total), new in box. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "nfcaaeswbf9ptld9",
    "title": "100% AUTHENTIC Tom Ford Men's Noir Extreme PARFUM Spray 3.4 oz 100ml SEALED",
    "brand": "Tom Ford",
    "category": "Fragrance",
    "sub": "Perfume & Parfum",
    "price": 179.95,
    "compareAt": 288.62,
    "image": "https://i.ebayimg.com/images/g/NfcAAeSwBf9ptLd9/s-l800.jpg",
    "rating": 4.9,
    "reviews": 118,
    "sold": 83,
    "condition": "New & Sealed",
    "blurb": "An unforgettable signature scent, beautifully composed.",
    "bestseller": true,
    "description": "Tom Ford Noir Extreme Parfum — a bold intensification of the iconic Noir Extreme in its richest concentration. Spicy cardamom opens over warm shimoga ginger, giving way to the deep sensuality of tonka bean and guaiacwood. The heart blooms with rose absolute and saffron, while a base of sandalwood, vanilla ember and Orpur® neroli oil anchors the scent in warm, masculine depth. A dramatic, long-lasting fragrance that merges spice, amber and wood for an unforgettable signature. Full size, 3.4 oz / 100 ml, brand new and sealed in box. 100% authentic, hand-inspected before it ships from a smoke-free studio. No returns on fragrance."
  },
  {
    "id": "s7saaosw0cdfbkq",
    "title": "ESTEE LAUDER Double Wear *ORIGINAL FORMULA Makeup Foundation 6.7oz/200ml Jumbo",
    "brand": "Estee Lauder",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 129.15,
    "compareAt": 370.45,
    "image": "https://i.ebayimg.com/images/g/S7sAAOSw0Cdf~bkQ/s-l800.jpg",
    "rating": 4.7,
    "reviews": 43,
    "sold": 150,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Estée Lauder Double Wear Stay-in-Place Makeup in the coveted jumbo counter bottle — 6.7 oz / 200 ml, nearly seven times the standard retail size. These are authentic professional color-matching bottles used at counters for shade-matching; brand new and never used, and they do not come in a retail box. Same iconic 24-hour formula: waterproof, transfer-resistant, natural matte finish, medium-to-full buildable coverage. Now discontinued and extremely rare in this size. Please know your shade before ordering, as there are no returns for hygiene reasons. Pick your shade from the menu.",
    "variation": {
      "label": "Shade",
      "options": [
        "0N1 Alabaster",
        "1C0 Shell",
        "1C1 Cool Bone",
        "1N0 Porcelain",
        "1N1 Ivory Nude",
        "1N2 Ecru",
        "1W0 Warm Porcelain",
        "1W1 Bone",
        "1W2 Sand",
        "2C0 Cool Vanilla",
        "2C1 Pure Beige",
        "2C3 Fresco",
        "2C4 Ivory Rose",
        "2N1 Desert Beige",
        "2N2 Buff",
        "2W0 Warm Vanilla",
        "2W1 Dawn",
        "2W2 Rattan",
        "3C1 Dusk",
        "3C2 Pebble",
        "3C3 Sandbar",
        "3N1 Ivory Beige",
        "3N2 Wheat",
        "3W1 Tawny",
        "3W1.5 Fawn",
        "3W2 Cashew",
        "4C1 Outdoor Beige",
        "4C2 Auburn",
        "4C3 Softan Soft Tan",
        "4N1 Shell Beige",
        "4N2 Spiced Sand",
        "4N3 Maple Sugar",
        "4W1 Honey Bronze",
        "4W2 Toasty Toffee",
        "4W3 Henna",
        "4W4 Hazel",
        "5C1 Rich Chestnut",
        "5C2 Sepia",
        "5N1 Rich Ginger",
        "5N1.5 Maple",
        "5N2 Amber Honey",
        "5W1 Bronze",
        "5W1.5 Cinnamon",
        "5W2 Rich Caramel",
        "6C1 Rich Cocoa",
        "6C2 Pecan",
        "6N1 Mocha",
        "6N2 Truffle",
        "6W1 Sandalwood",
        "6W2 Nutmeg",
        "7C1 Rich Mahogany",
        "7C2 Sienna",
        "7N1 Deep Amber",
        "7W1 Deep Spice",
        "8C1 Rich Java",
        "8N1 Espresso"
      ]
    }
  },
  {
    "id": "3koaaesw0dbouluj",
    "title": "BareMinerals BarePRO Performance Wear Liquid Foundation SPF 20 Discontinued",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 33.2,
    "compareAt": 58.95,
    "image": "https://i.ebayimg.com/images/g/3koAAeSw0dBouLUj/s-l800.jpg",
    "rating": 4.8,
    "reviews": 77,
    "sold": 190,
    "condition": "Rare / Discontinued",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "bareMinerals BarePRO Performance Wear liquid foundation gives full coverage with a natural matte finish, 24-hour transfer-resistant wear, and SPF 20. Mineral Lock Long-Wear Technology fuses mineral pigments with skin's own lipids to keep color true all day, while bamboo stem extract softens the look of pores and papaya enzyme smooths texture over time. Oil-free, paraben-free, sulfate-free, dermatologist-tested and cruelty-free. Discontinued and hard to find — full regular size 1 oz / 30 ml, new in box and sealed. Please know your color before ordering, as these are sealed for hygiene. Pick your shade from the menu.",
    "variation": {
      "label": "Color",
      "options": [
        "Porcelain 0.5",
        "Aspen 04",
        "Cashmere 06",
        "Warm Light 07",
        "Light Natural 09",
        "Linen 10.5"
      ]
    }
  },
  {
    "id": "hywaaeswewtotkgf",
    "title": "BareMinerals Original Mineral Veil Pressed Setting Powder .3oz/9g SHEER MEDIUM",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 24.95,
    "compareAt": 40.18,
    "image": "https://i.ebayimg.com/images/g/HYwAAeSwewtotkGF/s-l800.jpg",
    "rating": 4.9,
    "reviews": 120,
    "sold": 44,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": true,
    "description": "The original bareMinerals Mineral Veil pressed setting powder in Sheer Medium — a single universal-flattering shade. This talc-free, weightless formula locks in makeup and extends wear while blurring pores, fine lines and shine for a smooth, flawless matte finish with zero flashback in photos. Infused with Vitamin E to help defend against environmental stressors, and perfect for on-the-go touch-ups. Full regular size, 0.3 oz / 9 g, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Free of additives, binders, fillers and talc."
  },
  {
    "id": "klyaaesw7floulit",
    "title": "BareMinerals Loose Mineral Powder BLUSH in BEAUTY .03oz/0.85g Sealed",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Cheeks & Blush",
    "price": 19.99,
    "compareAt": 29.25,
    "image": "https://i.ebayimg.com/images/g/klYAAeSw7FlouLit/s-l800.jpg",
    "rating": 4.8,
    "reviews": 74,
    "sold": 159,
    "condition": "New & Sealed",
    "blurb": "A natural flush of buildable, radiant color.",
    "bestseller": false,
    "description": "bareMinerals Loose Mineral Powder Blush in Beauty — a warm, blushed pink that blends effortlessly into skin for fresh, vibrant, naturally luminous color. The 100% loose mineral formula is buildable and featherlight, with zero talc, binders, fillers or additives; gentle enough for all skin types including sensitive. Lot of 3 full-size compacts, 0.03 oz / 0.85 g each. New and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "zkcaaoswmahkp63",
    "title": "I IMAGE PREVENTION+ SPF 30 Daily Tinted Moisturizer Sunscreen 6oz",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 37,
    "compareAt": 38.95,
    "image": "https://i.ebayimg.com/images/g/ZkcAAOSwmahk~P63/s-l800.jpg",
    "rating": 5,
    "reviews": 146,
    "sold": 298,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": true,
    "description": "IMAGE PREVENTION+ Daily Tinted Moisturizer SPF 30 in the jumbo professional size — 6 oz / 170 g. This broad-spectrum pure mineral formula offers UVA/UVB protection while a sheer hint of color subtly evens skin tone for a warm, healthy glow. An antioxidant blend helps shield against environmental stressors like sun and wind that can accelerate dryness, discoloration and premature aging. The discontinued original formula in the pro size, hard to find. New and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "ofwaaoswx2phatu7",
    "title": "PML Pat McGrath Labs MOTHERSHIP EYESHADOW PALETTE 10 Eye Shadow",
    "brand": "Pat McGrath Labs",
    "category": "Makeup",
    "sub": "Eyes",
    "price": 104.95,
    "compareAt": 109.95,
    "image": "https://i.ebayimg.com/images/g/OfwAAOSwX2phatu7/s-l800.jpg",
    "rating": 4.7,
    "reviews": 44,
    "sold": 79,
    "condition": "New (Sealed)",
    "blurb": "Richly pigmented shades that blend like a dream.",
    "bestseller": false,
    "description": "The legendary Pat McGrath Labs Mothership palette — ten richly pigmented eyeshadows in a curated range of velvety mattes, glowing satins and dimensional metallics that blend like a dream and layer endlessly. Each shade is buttery-soft and intensely saturated, taking you from a soft daytime wash to a full editorial eye. New in box and sealed, 10 x 1.32 g / 0.047 oz net. 100% authentic, hand-inspected before it ships from a smoke-free studio. Choose your palette from the menu (each is sold individually).",
    "variation": {
      "label": "Palette",
      "options": [
        "Mothership V: Bronze Seduction",
        "Mothership VII: Divine Rose",
        "Mothership IX: Huetopian Dream"
      ]
    }
  },
  {
    "id": "vpaaaoswc3rlbqnc",
    "title": "I IMAGE PREVENTION+ SPF 50 Daily Ultimate Protection Moisturizer 3.2oz",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 59.95,
    "compareAt": 82.14,
    "image": "https://i.ebayimg.com/images/g/VPAAAOSwC3RlBQNc/s-l800.jpg",
    "rating": 4.7,
    "reviews": 45,
    "sold": 119,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Ultimate Protection Moisturizer SPF 50 — a sheer, lightweight daily moisturizer with broad-spectrum mineral UVA/UVB protection plus Digital Aging Defense to help combat the effects of blue light and environmental stressors. Free of octinoxate, oxybenzone, parabens and artificial fragrance. Comfortable enough for daily wear indoors or out, in any level of sun exposure. Sold as a 2-pack, 3.2 oz / 91 g each. New and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "lz4aaosw3edlrbsa",
    "title": "ESTEE LAUDER FUTURIST Hydra Rescue Moisturizing Foundation 1.2oz 35ml",
    "brand": "Estee Lauder",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 18.95,
    "compareAt": 42.95,
    "image": "https://i.ebayimg.com/images/g/LZ4AAOSw3edlRbSa/s-l800.jpg",
    "rating": 4.6,
    "reviews": 10,
    "sold": 108,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Estée Lauder Futurist Hydra Rescue Moisturizing Foundation delivers buildable medium-to-full coverage with a 12-hour radiant, natural-looking finish — while functioning like serious skincare underneath. Powered by IonCharged Water Complex, probiotic technology and chia-seed extract, it hydrates and nourishes skin throughout the day. SPF 45 adds daily sun protection in the same step. Breathable and lightweight, it won't clog pores and is free of parabens, phthalates, drying alcohol and mineral oil; dermatologist and ophthalmologist tested. Full regular size, 1.2 oz / 35 ml, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene."
  },
  {
    "id": "adqaaeswcppo5sok",
    "title": "BareMinerals Complexion Rescue Tinted Hydrating GEL CREAM SPF 30 1.18oz/35ml",
    "brand": "BareMinerals",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 14.99,
    "compareAt": 22.99,
    "image": "https://i.ebayimg.com/images/g/aDQAAeSwCPpo5soK/s-l800.jpg",
    "rating": 4.7,
    "reviews": 47,
    "sold": 293,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "bareMinerals Complexion Rescue Tinted Hydrating Gel Cream SPF 30 — the beloved original formula, now discontinued and increasingly hard to find. This lightweight, skin-perfecting tint delivers a natural, skin-true finish with buildable coverage and all-day hydration. The mineral SPF 30 protects while the gel-cream texture melts into skin for a seamless, breathable wear. Most shades are the original Gel Cream formula; Natural Pecan 05 is in the Tinted Moisturizer formula. Full regular size, 1.18 oz / 35 ml, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene. Pick your shade from the menu."
  },
  {
    "id": "7laaaeswngbpic0",
    "title": "ONE Image Skincare PREVENTION+ Daily Perfecting Primer SPF 50 1 oz/30ml READ",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 56.95,
    "compareAt": 59.95,
    "image": "https://i.ebayimg.com/images/g/7LAAAeSwNgBpi~c0/s-l800.jpg",
    "rating": 4.8,
    "reviews": 78,
    "sold": 376,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Perfecting Primer SPF 50 is a discontinued, three-in-one tinted skin perfector that primes, protects and perfects in a single step. The lightweight mineral formula delivers 100% mineral broad-spectrum UVA/UVB SPF 50 protection while antioxidants and plant-based extracts defend against environmental stressors. It smooths skin, minimizes the look of pores and fine lines, and leaves a long-lasting matte finish that keeps makeup in place all day. Rare and hard to find since discontinuation. Full size, 1 oz / 30 ml, new and sealed with box. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "vraaaeswthpovoxf",
    "title": "I IMAGE Daily Prevention SHEER MATTE Tinted Moisturizer SPF 30 2.6oz/73g",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 28.95,
    "compareAt": 37.34,
    "image": "https://i.ebayimg.com/images/g/vRAAAeSwTHpovOxf/s-l800.jpg",
    "rating": 4.6,
    "reviews": 20,
    "sold": 151,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Sheer Matte Tinted Moisturizer SPF 30 is a mattifying daily moisturizer with XOSM Technology that smooths skin's appearance and controls shine throughout the day. Oil-reducing microspheres absorb excess oil for a lasting satin-matte finish, while transparent zinc oxide delivers broad-spectrum UVA/UVB protection plus blue light defense. A neutral, blendable tint minimizes any white cast on all skin tones. Free of oxybenzone, octinoxate, parabens and fragrance; non-comedogenic, physician-formulated, dermatologist-tested and PETA certified animal test-free. Recommended by The Skin Cancer Foundation. Full size, 2.6 oz / 73 g, new and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "vfuaaoswukrgopdf",
    "title": "ESTEE LAUDER Double Wear LIGHT SOFT MATTE Makeup Foundation Jumbo 6.7oz",
    "brand": "Estee Lauder",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 94.95,
    "compareAt": 344.95,
    "image": "https://i.ebayimg.com/images/g/VFUAAOSwuKRgopdF/s-l800.jpg",
    "rating": 4.9,
    "reviews": 115,
    "sold": 126,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Estée Lauder's Double Wear Light Soft Matte Hydra Makeup in the rare jumbo 6.7 oz bottle — nearly seven times the retail size. A 24-hour soft-matte foundation that's sweat-, humidity- and water-resistant, infused with hyaluronic acid to keep skin feeling comfortable while controlling shine. Light-to-medium buildable coverage that stays color true and won't clog pores; oil-free and fragrance-free, for all skin types. Just discontinued and hard to find. These are authentic counter color-matching bottles — brand new and never used, and they do not come in a retail box. Please know your shade before ordering, as there are no returns for hygiene reasons. Pick your shade from the menu.",
    "variation": {
      "label": "Shade",
      "options": [
        "1C0 Shell",
        "1W2 Sand",
        "2N1 Desert Beige",
        "3C2 Pebble",
        "3W1 Tawny",
        "3W1.5 Fawn",
        "4C3 Softan Soft Tan",
        "5N1 Rich Ginger",
        "5W1 Bronze",
        "6C1 Rich Cocoa",
        "6N2 Truffle",
        "6W1 Sandalwood",
        "7N1 Deep Amber"
      ]
    }
  },
  {
    "id": "uxwaaosw6czknd",
    "title": "I IMAGE PREVENTION+ SPF 50 Daily Ultimate Protection Moisturizer 3.2oz",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 34.95,
    "compareAt": 45.1,
    "image": "https://i.ebayimg.com/images/g/UxwAAOSw6cZk~n-d/s-l800.jpg",
    "rating": 4.6,
    "reviews": 20,
    "sold": 55,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Ultimate Protection Moisturizer SPF 50 — a sheer, lightweight daily moisturizer with broad-spectrum mineral UVA/UVB protection and Digital Aging Defense to help fight the effects of blue light and environmental stressors. A specialized hydrolyzed pea protein defends against the elements that age skin indoors and out. Free of octinoxate, oxybenzone, parabens and artificial fragrances. Recently discontinued and authentic stock is increasingly scarce — note expiration dates have been removed per seller disclosure, with 12 months effective life from opening. Full size, 3.2 oz / 91 g, new and sealed. Some units come with box, some without (sourced from limited edition kits). 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "xzcaaesw3k1oumi1",
    "title": "bareMinerals EYE Brightener SPF 20 - WELL RESTED - 2g/0.07oz Concealer",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Concealer",
    "price": 15.95,
    "compareAt": 22.26,
    "image": "https://i.ebayimg.com/images/g/xZcAAeSw3K1ouMi1/s-l800.jpg",
    "rating": 4.7,
    "reviews": 53,
    "sold": 169,
    "condition": "New (Sealed)",
    "blurb": "Brightens, covers, and smooths in one swipe.",
    "bestseller": false,
    "description": "bareMinerals Eye Brightener in Well-Rested — a vegan under-eye brightener that makes you look well-rested even when you're not. The lightweight formula instantly brightens the look of dark circles, diminishes the appearance of puffiness and fatigue, and delivers a natural-looking luminous finish, all while protecting with broad-spectrum mineral SPF 20. Full regular size, 2 g / 0.07 oz, new and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "uxwaaeswycxougow",
    "title": "BareMinerals Butter Drench Restorative Rich Face Cream Full Size 1.7oz /50g",
    "brand": "BareMinerals",
    "category": "Skincare",
    "sub": "Moisturizers & Creams",
    "price": 32,
    "compareAt": 52.4,
    "image": "https://i.ebayimg.com/images/g/UxwAAeSwYcxougow/s-l800.jpg",
    "rating": 4.9,
    "reviews": 128,
    "sold": 34,
    "condition": "New (Sealed)",
    "blurb": "Deeply hydrating care for soft, supple skin.",
    "bestseller": true,
    "description": "bareMinerals Butter Drench Restorative Rich Cream is a deeply moisturizing face cream formulated for dry to very dry skin. Shea butter restores radiance while a blend of peptides, ceramides and amino acids smooths roughness and visibly minimizes wrinkles over time. The intuitive mineral moisture system saturates skin with rejuvenating hydration that lasts all day. Non-comedogenic and suitable for daily use morning and evening — wear alone or layer under makeup. The original formula, recently discontinued. Full regular size, 1.7 oz / 50 g, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "yd4aaosw7lfnga2g",
    "title": "I IMAGE PREVENTION+ SPF 30 Daily MATTE MOISTURIZER 6oz/170g PRO Sz *Read",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 49.95,
    "compareAt": 83.86,
    "image": "https://i.ebayimg.com/images/g/YD4AAOSw7lFnGa2G/s-l800.jpg",
    "rating": 5,
    "reviews": 141,
    "sold": 76,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": true,
    "description": "IMAGE PREVENTION+ Daily Matte Moisturizer SPF 30 in the jumbo professional size — 6 oz / 170 g. This oil-free, broad-spectrum UVA/UVB moisturizer uses micro-sponge technology to absorb surface oils and maintain a shine-free matte finish all day. A next-generation antioxidant blend defends against free radicals from sun and environmental exposure. Water-resistant and ideal as a daily moisturizer or makeup primer; best for combination, oily and acne-prone skin. Free of parabens, phthalates, mineral oils, artificial fragrances, synthetic dyes and animal testing. Discontinued and hard to find in this pro size, properly handled and stored. New in box and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "bogaaeswaztovixc",
    "title": "bareMinerals Gen Nude Powder Pressed BLUSH 0.21oz/6g",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Cheeks & Blush",
    "price": 16.95,
    "compareAt": 24.95,
    "image": "https://i.ebayimg.com/images/g/bOgAAeSwaZtovIXC/s-l800.jpg",
    "rating": 4.9,
    "reviews": 129,
    "sold": 81,
    "condition": "New & Sealed",
    "blurb": "A natural flush of buildable, radiant color.",
    "bestseller": true,
    "description": "bareMinerals Gen Nude Powder Blush is an ultra-silky, talc-free pressed blush that builds and blends seamlessly for a diffused, soft-focus flush of color with no harsh edges. The mineral-rich formula delivers buildable sheer-to-medium color and a natural soft-matte finish, smooths the look of pores, and wears beautifully all day. Vegan, cruelty-free, gluten-free and free of parabens, talc, synthetic fragrance, SLS and PEG. Full regular size, 0.21 oz / 6 g, new in box. 100% authentic, hand-inspected and sanitized before it ships. Please know your color before ordering, as these are sealed for hygiene. Pick your color from the menu.",
    "variation": {
      "label": "Color",
      "options": [
        "Call My Blush",
        "Pretty In Pink",
        "Pink Me Up",
        "Peachy Keen"
      ]
    }
  },
  {
    "id": "jiaaosw1rxlvdcy",
    "title": "Smashbox Halo Fresh PERFECTING POWDER .35oz/10g - * Fresh *",
    "brand": "Smashbox",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 27.5,
    "compareAt": 67.95,
    "image": "https://i.ebayimg.com/images/g/J~IAAOSw1rxlVDcY/s-l800.jpg",
    "rating": 4.9,
    "reviews": 111,
    "sold": 359,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Smashbox Halo Fresh Perfecting Powder is a light-coverage, long-wearing loose powder with a built-in Fresh-Grind Powderizer that grinds fresh powder on demand for a soft, natural, airbrushed finish that won't crease or cake. It sets makeup and blurs imperfections while keeping skin looking fresh all day. Full size, 0.35 oz / 10 g, new in box. Just discontinued and hard to find. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio. Pick your shade from the menu.",
    "variation": {
      "label": "Color",
      "options": [
        "Fair",
        "Dark/Neutral"
      ]
    }
  },
  {
    "id": "nneaaeswdefoulhd",
    "title": "BareMinerals Loose Mineral Powder BLUSH in BEAUTY .03oz/0.85g Sealed + Gift",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Cheeks & Blush",
    "price": 9.49,
    "compareAt": 9.99,
    "image": "https://i.ebayimg.com/images/g/nNEAAeSwDEFouLhd/s-l800.jpg",
    "rating": 4.9,
    "reviews": 118,
    "sold": 319,
    "condition": "New & Sealed",
    "blurb": "A natural flush of buildable, radiant color.",
    "bestseller": true,
    "description": "bareMinerals Loose Mineral Powder Blush in Beauty — a warm, blushed pink that blends effortlessly into skin for fresh, vibrant, naturally luminous color. Made with 100% loose minerals, this lightweight vegan formula delivers buildable sheer-to-medium coverage with a radiant glow and zero talc, binders, fillers or additives. Dermatologist-tested and free of parabens, formaldehyde, gluten, synthetic fragrance, PEGs and SLS; gentle enough for all skin types including sensitive. Full regular size, 0.03 oz / 0.85 g, new and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "a78aaoswilvhlwzx",
    "title": "Eminence BAMBOO FIRMING FLUID Card Samples 2ml/.07oz Total 1.2oz=F/S Value$62",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 31.99,
    "compareAt": 50.03,
    "image": "https://i.ebayimg.com/images/g/A78AAOSwILVhlWzx/s-l800.jpg",
    "rating": 4.9,
    "reviews": 105,
    "sold": 305,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": false,
    "description": "Eminence Organic Bamboo Firming Fluid in a lot of 18 sample cards — 2 ml each, totaling 1.26 oz / 36 ml, equivalent to a full-size bottle. This award-winning firming serum combines the strengthening properties of bamboo and coconut for deep hydration, plus a Natural Retinol Alternative and Swiss Green Apple Stem Cells to visibly tighten skin, reduce signs of aging and improve the look of elasticity over time. Skin appears smoother, silkier and firmer with continued use. Ideal for normal to dry and mature skin types. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "uheaaoswmdngdsx",
    "title": "(1) I IMAGE Skincare MD Restoring Recovery EYE GEL .5oz (15ml)",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Eye Care",
    "price": 56.95,
    "compareAt": 59.95,
    "image": "https://i.ebayimg.com/images/g/uhEAAOSwM~dnGDSX/s-l800.jpg",
    "rating": 4.7,
    "reviews": 35,
    "sold": 361,
    "condition": "New & Sealed",
    "blurb": "Depuffs, firms, and brightens the delicate eye area.",
    "bestseller": false,
    "description": "IMAGE MD Restoring Recovery Eye Gel is a physician-formulated, hydrating eye treatment that visibly reduces fine lines, wrinkles, puffiness and dark circles around the eye area. Advanced Delivery Technology drives a targeted peptide complex deep into skin to improve the look of wrinkles and loss of firmness, while marine collagen microspheres plump the appearance of crepey skin and restore a bright, well-rested look. Discontinued and hard to find — retail $112. Full size, 0.5 oz / 15 ml, new in box and sealed, properly stored in a climate-controlled smoke-free environment. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "hxkaaeswfdnocxaf",
    "title": "MAC Studio Fix Powder Plus Foundation Original Formula 0.52oz",
    "brand": "MAC",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 26.55,
    "compareAt": 43.95,
    "image": "https://i.ebayimg.com/images/g/hXkAAeSwfdNocxaF/s-l800.jpg",
    "rating": 4.8,
    "reviews": 70,
    "sold": 85,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "MAC Studio Fix Powder Plus Foundation in the beloved original formula — a one-step powder and foundation that delivers smooth, full coverage with a natural matte finish in a single sweep. Use it dry for buildable medium-to-full coverage, or damp for fuller coverage; it controls shine and lasts all day. Full size, 0.52 oz / 15 g, new in box and fresh. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio. Please know your shade before ordering, as these are sealed for hygiene. Pick your color from the menu.",
    "variation": {
      "label": "Color",
      "options": [
        "N5",
        "NC15",
        "NC20",
        "NC25",
        "NC30",
        "NC41",
        "NC42",
        "NC43.5",
        "NC44.5",
        "NC45",
        "NC46",
        "NC47",
        "NW30",
        "NW33",
        "NW35",
        "NW40",
        "NW44",
        "NW50",
        "C3.5",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C40"
      ]
    }
  },
  {
    "id": "ploaaoswnbflgttj",
    "title": "Obagi Nu-Derm EXFODERM #4 AM Skin Smoothing LOTION 2oz/57g New & Sealed",
    "brand": "Obagi",
    "category": "Skincare",
    "sub": "Moisturizers & Creams",
    "price": 47.45,
    "compareAt": 49.95,
    "image": "https://i.ebayimg.com/images/g/PLoAAOSwNbFlGttJ/s-l800.jpg",
    "rating": 4.9,
    "reviews": 111,
    "sold": 105,
    "condition": "New & Sealed",
    "blurb": "Deeply hydrating care for soft, supple skin.",
    "bestseller": false,
    "description": "Obagi Nu-Derm Exfoderm (#4 AM) is a lightweight exfoliating lotion that removes dull, dead skin cells to reveal fresh, brighter and more radiant skin underneath. Formulated for normal to dry and sensitive skin types, it is used daily in the morning as step 4 of the Nu-Derm system; pairs with the #5 PM Blend Fx cream for enhanced results. Full size, 2 oz / 57 g, new and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "ixqaaeswvb9oukno",
    "title": "bareMinerals BarePro 16hr Skin-Perfecting Powder Foundation 8g/0.28oz",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 24.95,
    "compareAt": 25.95,
    "image": "https://i.ebayimg.com/images/g/ixQAAeSwvB9oukNO/s-l800.jpg",
    "rating": 4.7,
    "reviews": 54,
    "sold": 356,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "bareMinerals BarePro 16HR Skin-Perfecting Powder Foundation is a sweat-, humidity- and transfer-resistant natural matte foundation that delivers 16 hours of breathable full coverage while visibly evening skin tone and texture over time. It absorbs oil and controls shine for up to 24 hours, for a flawless, long-wearing finish. Original formula, just discontinued and mostly sold out. Full regular size, 0.28 oz / 8 g, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your color before ordering, as these are sealed for hygiene. Pick your color from the menu.",
    "variation": {
      "label": "Color",
      "options": [
        "Light 22 Cool",
        "Light 25 Neutral"
      ]
    }
  },
  {
    "id": "nkuaaesw8c5oulvi",
    "title": "BareMinerals BarePRO Performance Wear Liquid Foundation SPF 20 LIGHT NATURAL 09",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 37.95,
    "compareAt": 39.95,
    "image": "https://i.ebayimg.com/images/g/nkUAAeSw8c5ouLvI/s-l800.jpg",
    "rating": 4.6,
    "reviews": 13,
    "sold": 156,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "bareMinerals BarePRO Performance Wear Liquid Foundation in Light Natural 09 — a full-coverage, 24-hour foundation with a natural matte finish and SPF 20. Mineral Lock Long-Wear Technology blends mineral pigments with skin's own lipids to lock in all-day color-true coverage, while natural bamboo stem extract softens the look of pores and papaya enzymes gently improve skin texture both immediately and over time. Transfer-resistant and photo-friendly. Oil-free, paraben-free, sulfate-free, phthalate-free, dermatologist-tested, non-acnegenic, non-comedogenic and cruelty-free. Full regular size, 1 oz / 30 ml, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "l5caaeswiknohqau",
    "title": "I IMAGE PREVENTION+ SPF 30 Daily MATTE MOISTURIZER 3.2oz/91g *Discontinued",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 26.95,
    "compareAt": 39.58,
    "image": "https://i.ebayimg.com/images/g/L5cAAeSwIkNohQAu/s-l800.jpg",
    "rating": 4.8,
    "reviews": 75,
    "sold": 86,
    "condition": "Rare / Discontinued",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Matte Moisturizer SPF 30 — an oil-free, broad-spectrum UVA/UVB moisturizer that uses micro-sponge technology to absorb surface oils and keep skin shine-free all day. A next-generation antioxidant blend defends against free radicals from sun and environmental exposure. Water-resistant and excellent as a daily moisturizer or makeup primer; best for combination, oily and acne-prone skin. Free of parabens, phthalates, mineral oils, artificial fragrances and synthetic dyes. Discontinued and hard to find — properly stored and still fresh. Full size, 3.2 oz / 91 g, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "49aaaoswqypniymw",
    "title": "CLINIQUE CHUBBY in the NUDE Foundation Makeup Travel GWP .12oz/3.4g",
    "brand": "Clinique",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 42.7,
    "compareAt": 54.95,
    "image": "https://i.ebayimg.com/images/g/49AAAOSwQypnIYmW/s-l800.jpg",
    "rating": 4.9,
    "reviews": 102,
    "sold": 180,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Clinique Chubby in the Nude Foundation Stick is a creamy, moisturizing stick that doubles as foundation and concealer — build it from sheer to moderate coverage for a natural, skin-perfecting finish that evens tone and lasts all day. Twist up and swipe on, then blend with fingertips; long-wearing, oil-free and great for full-face coverage or quick touch-ups. Works for all skin types. Discontinued and hard to find. Travel deluxe size, 0.12 oz / 3.4 g (more than half the full size), new and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene. Pick your shade from the menu.",
    "variation": {
      "label": "Shade",
      "options": [
        "09 'Normous Neutral",
        "14 Voluptuous Vanilla"
      ]
    }
  },
  {
    "id": "0n0aaeswhynozpi",
    "title": "I IMAGE PREVENTION+ SPF 30 Daily MATTE MOISTURIZER 3.2oz/91g *Discontinued",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 189.95,
    "compareAt": 258.73,
    "image": "https://i.ebayimg.com/images/g/0n0AAeSwhyNoZ~pI/s-l800.jpg",
    "rating": 4.7,
    "reviews": 42,
    "sold": 73,
    "condition": "Rare / Discontinued",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Matte Moisturizer SPF 30 — a 10-bottle bundle for those who want to stock up on this discontinued favorite. Each bottle is the full size, 3.2 oz / 91 g. Oil-free, broad-spectrum UVA/UVB protection with micro-sponge technology to absorb surface oils and maintain a shine-free matte finish all day. Antioxidant blend defends against environmental free radicals. Water-resistant, excellent as both a daily moisturizer and a makeup primer; best for combination, oily and acne-prone skin. Free of parabens, phthalates, mineral oils, artificial fragrances and synthetic dyes. All 10 bottles are new, sealed and properly stored. 100% authentic, hand-inspected before they ship."
  },
  {
    "id": "yjkaaeswkvptq1",
    "title": "bareMinerals ORIGINAL Loose Powder Foundation SPF 15 Sunscreen 8g/.28oz",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 18.95,
    "compareAt": 29.95,
    "image": "https://i.ebayimg.com/images/g/yjkAAeSwk~VpT-q1/s-l800.jpg",
    "rating": 4.9,
    "reviews": 106,
    "sold": 41,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "bareMinerals ORIGINAL Loose Powder Foundation is the iconic mineral makeup that started it all — a weightless loose powder that buffs on for naturally radiant, buildable coverage with broad-spectrum SPF 15. Made with good-for-skin minerals and free of harsh chemicals, it evens tone, blurs imperfections and feels like nothing on the skin, so it's gentle enough to sleep in. Full regular size, 0.28 oz / 8 g, new and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your color before ordering, as these are sealed for hygiene. Pick your color from the menu.",
    "variation": {
      "label": "Color",
      "options": [
        "Golden Fair 04",
        "Fairly Medium 05",
        "Neutral Ivory 06",
        "Golden Beige 13",
        "Tan 19",
        "Tan Nude 17"
      ]
    }
  },
  {
    "id": "4tcaaosw1wtffgqd",
    "title": "Eminence Arctic Berry Peptide Radiance CREAM Card Samples 3ml/.10oz + Bonus",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 18.99,
    "compareAt": 31.28,
    "image": "https://i.ebayimg.com/images/g/4TcAAOSw1wtffgqd/s-l800.jpg",
    "rating": 5,
    "reviews": 131,
    "sold": 86,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": true,
    "description": "Eminence Organic Arctic Berry Peptide Radiance Cream in a lot of 6 sample cards — 3 ml each, 18 ml total. This all-powerful daily moisturizer features an exclusive Peptide Illuminating Complex that visibly smooths and reduces the look of wrinkles, firms and plumps skin, calms the appearance of irritation and inflammation, and leaves the complexion luminous and even-toned. Ideal for normal to dry skin types. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "k00aaoswdqhnxqon",
    "title": "Authentic Chanel Rouge Coco BLOOM LIPSTICK Lip Colour Color F/S .1oz/3g",
    "brand": "CHANEL",
    "category": "Makeup",
    "sub": "Lips",
    "price": 49.95,
    "compareAt": 83.55,
    "image": "https://i.ebayimg.com/images/g/k00AAOSwDQhnXQon/s-l800.jpg",
    "rating": 5,
    "reviews": 139,
    "sold": 189,
    "condition": "New (Sealed)",
    "blurb": "Long-wear color with a luxurious, comfortable finish.",
    "bestseller": true,
    "description": "CHANEL Rouge Coco Bloom Lipstick — a full-coverage lip color with a vivid, high-shine finish and a lightweight, moisturizing feel. The long-wearing formula delivers intense, buildable color in a single stroke with a comfortable, hydrating texture that keeps lips soft. Full size, 0.1 oz / 3 g, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Pick your shade from the menu (each sold individually)."
  },
  {
    "id": "hlaaaoswthlnjeep",
    "title": "Erno Laszlo FIRMARINE CLEANSING OIL 6.6oz/190ml Sealed New NO Box Discont.",
    "brand": "Prestige Beauty",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 56.95,
    "compareAt": 59.95,
    "image": "https://i.ebayimg.com/images/g/HLAAAOSwThlnJEep/s-l800.jpg",
    "rating": 4.8,
    "reviews": 69,
    "sold": 248,
    "condition": "New & Sealed",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Erno Laszlo Firmarine Cleansing Oil is an ultra-light luxury facial cleansing oil that removes impurities and makeup while leaving skin visibly smoother, firmer and more lifted. The formula combines the Marine Complex — potent Spirulina Maxima algae with mineral-rich seawater — to lift and firm, alongside nourishing jojoba and olive oils for deep moisture, and antioxidant green tea, cucumber extract and vitamin E to protect against free radical damage. Massage generously onto dry skin in circular motions, then follow with a cleansing bar to complete the double-cleanse ritual. Full size, 6.6 oz / 190 ml, new and sealed (no box — tester bottle). Discontinued and hard to find. 100% authentic, hand-inspected before it ships from a smoke-free studio."
  },
  {
    "id": "mvwaaeswwvdo6b1",
    "title": "Estee Lauder Double Wear MAXIMUM COVER Camouflage Makeup Foundation 1oz/30ml",
    "brand": "Estee Lauder",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 29.95,
    "compareAt": 39.95,
    "image": "https://i.ebayimg.com/images/g/mVwAAeSwWVdo6B1~/s-l800.jpg",
    "rating": 4.8,
    "reviews": 66,
    "sold": 359,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Estée Lauder Double Wear Maximum Cover Camouflage Makeup is the brand's highest-coverage foundation — a long-wearing, full-coverage formula designed to conceal and camouflage blemishes, redness, discoloration and uneven skin tone for a flawless, natural-looking finish. The 24-hour wear formula is transfer-resistant and stays color true without touch-ups. Discontinued and increasingly hard to find. Full regular size, 1 oz / 30 ml, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene."
  },
  {
    "id": "39maaoswbuffglvn",
    "title": "Eminence BAMBOO Age Corrective MASQUE MASK Card Samples 3g/.1oz ea + Bonus",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 15.19,
    "compareAt": 15.99,
    "image": "https://i.ebayimg.com/images/g/39MAAOSwbuFfglVN/s-l800.jpg",
    "rating": 4.9,
    "reviews": 108,
    "sold": 30,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": false,
    "description": "Eminence Organic Bamboo Age Corrective Masque in a lot of 6 sample cards — 3 g each, 18 g total. This award-winning age-repairing mask uses powerful anti-aging technology to instantly firm and tighten skin, visibly reduce signs of aging, improve elasticity and boost moisture and hydration levels. A collagen-boosting treatment for normal to dry skin types. Apply a thin layer to cleansed skin for 5–10 minutes, then remove with a damp cloth. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "cbuaaoswdavfij1t",
    "title": "Eminence Calm Skin Arnica Booster SERUM Card Samples 2ml/.07oz ea Fresh",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 13.99,
    "compareAt": 23.07,
    "image": "https://i.ebayimg.com/images/g/cbUAAOSwdAVfij1T/s-l800.jpg",
    "rating": 5,
    "reviews": 132,
    "sold": 225,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": true,
    "description": "Eminence Organic Calm Skin Arnica Booster Serum in a lot of 6 sample cards — 2 ml each, 12 ml total. This award-winning extra-strength serum and product enhancer is infused with arnica, chamomile and lavender to calm and balance sensitive skin. It visibly reduces the appearance of redness and irritation, tones and enriches the complexion, and stimulates oxygenation and blood circulation. Use alone on affected areas up to 3 times daily, or blend 2–3 drops into an Eminence masque or moisturizer to boost results. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "wm8aaoswfrlkqfv",
    "title": "I IMAGE PREVENTION+ SPF 30 Daily Hydrating Moisturizer Sunscreen 3.2oz/91g",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 28.95,
    "compareAt": 43.61,
    "image": "https://i.ebayimg.com/images/g/Wm8AAOSwFRlk-qFv/s-l800.jpg",
    "rating": 4.8,
    "reviews": 87,
    "sold": 376,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": false,
    "description": "IMAGE PREVENTION+ Daily Hydrating Moisturizer SPF 30 — an all-mineral, hydrating daily moisturizer with broad-spectrum UVA/UVB protection. The updated formula uses a new zinc oxide that blends in seamlessly for a sheer, weightless finish that wears beautifully under makeup or on its own. Key actives include hydrolyzed pea protein and an antioxidant blend to defend against environmental aging. Free of parabens, phthalates, mineral oils, artificial fragrances, synthetic dyes and animal testing. Full size, 3.2 oz / 91 g, new and sealed. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio."
  },
  {
    "id": "wikaaoswo95bmddm",
    "title": "Lancome Makeup Foundation Jumbo Pro Size Dram 4 fl oz New Type/Color",
    "brand": "Lancome",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 129.95,
    "compareAt": 179.95,
    "image": "https://i.ebayimg.com/images/g/wIkAAOSwO95bmDdM/s-l800.jpg",
    "rating": 4.8,
    "reviews": 86,
    "sold": 280,
    "condition": "New & Sealed",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "Lancôme foundation in the coveted jumbo Pro / counter dram size — roughly 3.82 fl oz, several times the standard retail bottle. These are authentic professional color-matching bottles, brand new and never used. Choose your formula from the menu: each Lancôme base has its own finish and benefits, from the radiant anti-aging coverage of Absolue Bx and Rénergie Lift to the luminous Teint Visionnaire and Teint Miracle, the buildable 24-hour Teint Idole Ultra, the breathable Teint Idole Fresh Wear, and skin-perfecting Photogenic Lumessence. 100% authentic, hand-inspected and sanitized before it ships from a smoke-free studio. Please know your formula before ordering, as there are no returns for hygiene reasons. Pick your formula from the menu (each is sold individually).",
    "variation": {
      "label": "Formula",
      "options": [
        "AL - Absolue Bx",
        "PL - Photogenic Lumessence",
        "RLM - Renergie Lift",
        "TIU - Teint Idole Ultra 24H",
        "TM - Teint Miracle",
        "TV - Teint Visionnaire",
        "TI FW - Teint Idole Fresh Wear"
      ]
    }
  },
  {
    "id": "wduaaoswzojffgv1",
    "title": "Eminence Neroli Age Corrective EYE SERUM Card Samples 2ml/.07oz each +Bonus",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 13.29,
    "compareAt": 13.99,
    "image": "https://i.ebayimg.com/images/g/WdUAAOSwzoJffgV1/s-l800.jpg",
    "rating": 4.7,
    "reviews": 50,
    "sold": 92,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": false,
    "description": "Eminence Organic Neroli Age Corrective Eye Serum in a lot of 6 sample cards — 2 ml each, 12 ml total. This award-winning eye serum combines neroli oil, coconut water and green apple stem cell technology to visibly firm the skin around the eyes, reduce the appearance of crow's feet and fine lines, balance moisture levels and leave the eye area looking smooth and rejuvenated. Suitable for all skin types, especially mature skin. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "10yaaoswoilfijwt",
    "title": "Eminence Lavender Age Corrective NIGHT CONCENTRATE Card Samples 2ml/.07oz",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 14.24,
    "compareAt": 14.99,
    "image": "https://i.ebayimg.com/images/g/10YAAOSwoilfijwT/s-l800.jpg",
    "rating": 4.7,
    "reviews": 54,
    "sold": 225,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": false,
    "description": "Eminence Organic Lavender Age Corrective Night Concentrate in a lot of 6 sample cards — 2 ml each, 12 ml total. This concentrated overnight treatment blends calming lavender with age-corrective actives to visibly firm skin, reduce fine lines and replenish moisture while you sleep. Leaves skin looking smoother and more rejuvenated by morning. Suitable for normal to dry and mature skin types. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "vkiaaoswfjhlu7lw",
    "title": "I IMAGE PREVENTION+ Daily Defense LIP Enhancer SPF 15 .25oz (Lot x3) READ*",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Sunscreen & SPF",
    "price": 22.36,
    "compareAt": 27.95,
    "image": "https://i.ebayimg.com/images/g/VKIAAOSwFjhlU7LW/s-l800.jpg",
    "rating": 4.9,
    "reviews": 125,
    "sold": 132,
    "condition": "New (Sealed)",
    "blurb": "Daily broad-spectrum protection you'll love to wear.",
    "bestseller": true,
    "description": "IMAGE PREVENTION+ Daily Defense Lip Enhancer SPF 15 — a discontinued lip treatment that hydrates, protects and visibly plumps lips in one step. Formulated with peptides and marine collagen to help boost lip fullness and minimize the signs of sunburn and chapping, with SPF 15 for daily sun protection. Plant-derived stem cell technology supports cell longevity for advanced anti-aging benefit. Sold as a pack of 3 full-size tubes, 0.25 oz / 7 g each, new and sealed (no box). Discontinued and final sale. 100% authentic, hand-inspected and sanitized before they ship."
  },
  {
    "id": "nskaaeswdn5oyedz",
    "title": "Estee Lauder Double Wear SHEER Long Wear Foundation SPF19 1oz/30ml",
    "brand": "Estee Lauder",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 19.96,
    "compareAt": 37.96,
    "image": "https://i.ebayimg.com/images/g/NSkAAeSwDN5oyeDz/s-l800.jpg",
    "rating": 5,
    "reviews": 140,
    "sold": 349,
    "condition": "New (Sealed)",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": true,
    "description": "Estée Lauder Double Wear Sheer Long-Wear Makeup is weightless, fresh-feeling matte foundation with all-day staying power. The undetectable formula gives sheer-to-light buildable coverage that evens skin tone and smooths texture for a naturally perfected, softly diffused matte finish. It stays color true through 12 hours of wear without creasing, caking or streaking, resists sweat and humidity, and adds SPF 19 plus antioxidants to help shield against UV and pollution. Oil-free, fragrance-free and dermatologist-tested for all skin types; so easy you can blend it on with fingertips. Full regular size, 1 oz / 30 ml, new in box and sealed. 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene. Pick your shade from the menu.",
    "variation": {
      "label": "Shade",
      "options": [
        "1W1 Bone",
        "4N2 Spiced Sand",
        "4W1 Honey Bronze",
        "5N2 Amber Honey",
        "5W2 Rich Caramel",
        "6N2 Truffle",
        "6W1 Sandalwood",
        "7N1 Deep Amber",
        "8C1 Rich Java",
        "8N1 Espresso"
      ]
    }
  },
  {
    "id": "apuaaeswus1opzu",
    "title": "BareMinerals ORIGINAL Liquid MINERAL Foundation SPF 20 Discontinued NO BOX",
    "brand": "BareMinerals",
    "category": "Makeup",
    "sub": "Foundation & Powder",
    "price": 19.95,
    "compareAt": 28.79,
    "image": "https://i.ebayimg.com/images/g/APUAAeSwus1o-pZu/s-l800.jpg",
    "rating": 4.8,
    "reviews": 68,
    "sold": 324,
    "condition": "Rare / Discontinued",
    "blurb": "Flawless, skin-true coverage that lasts all day.",
    "bestseller": false,
    "description": "bareMinerals ORIGINAL Liquid Mineral Foundation SPF 20 — the liquid evolution of the iconic mineral formula, delivering buildable medium-to-full coverage with a natural, skin-true finish and broad-spectrum SPF 20. Made with skin-loving minerals, it's lightweight and breathable on skin, evening tone and blurring imperfections without feeling heavy. Discontinued and increasingly hard to find. Full regular size, 1 oz / 30 ml, new and sealed (no retail box). 100% authentic, hand-inspected and sanitized before it ships. Please know your shade before ordering, as these are sealed for hygiene. Pick your shade from the menu."
  },
  {
    "id": "uwsaaoswf1lkox0i",
    "title": "1- I IMAGE The MAX Stem Cell Facial CLEANSER - New Sealed 4 oz",
    "brand": "IMAGE Skincare",
    "category": "Skincare",
    "sub": "Cleansers",
    "price": 18.99,
    "compareAt": 25.45,
    "image": "https://i.ebayimg.com/images/g/uWsAAOSwf1lkoX0i/s-l800.jpg",
    "rating": 4.7,
    "reviews": 36,
    "sold": 142,
    "condition": "New & Sealed",
    "blurb": "Gently lifts away impurities without stripping.",
    "bestseller": false,
    "description": "IMAGE THE MAX Stem Cell Facial Cleanser — a luxurious creamy wash powered by an advanced polypeptide complex and plant-derived stem cell technology that transforms cleansing into a skin-rejuvenating ritual. Free of sulfates, parabens and acids, it gently balances and optimizes the skin's pH while carefully selected botanicals nourish and shield against daily environmental pollutants. Physician-formulated for all skin types, including aging and sensitive skin. Discontinued original formula, hard to find. Full size, 4 oz / 118 ml, new and sealed (sourced from a collection set). 100% authentic, hand-inspected and sanitized before it ships."
  },
  {
    "id": "wvmaaoswmcpfgp9v",
    "title": "Eminence Monoi Age Corrective Exfoliating CLEANSER Card Samples 3ml/.10oz",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 14.24,
    "compareAt": 14.99,
    "image": "https://i.ebayimg.com/images/g/WVMAAOSwmCpfgP9V/s-l800.jpg",
    "rating": 4.9,
    "reviews": 97,
    "sold": 169,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": false,
    "description": "Eminence Organic Monoi Age Corrective Exfoliating Cleanser in a lot of 12 sample cards — 3 ml each, 36 ml total. This award-winning multi-action exfoliating cleanser is infused with exotic monoi to wash away impurities, remove surface debris and leave skin polished, primed and visibly smoother. It minimizes the appearance of pores, revitalizes the complexion and prepares skin for maximum absorption of serums and moisturizers. Cruelty-free and free of parabens, SLS, synthetic dyes, petrochemicals, animal by-products, phthalates, GMOs and triclosan. For normal to dry skin types. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  },
  {
    "id": "jlgaaoswvddfbqxm",
    "title": "Eminence Wild Plum EYE CREAM Card Samples 2ml/.07oz each -Total 12ml Fresh",
    "brand": "Eminence",
    "category": "Skincare",
    "sub": "Samples & Sets",
    "price": 16.14,
    "compareAt": 16.99,
    "image": "https://i.ebayimg.com/images/g/jLgAAOSwVDdfbQXM/s-l800.jpg",
    "rating": 4.6,
    "reviews": 10,
    "sold": 246,
    "condition": "New (Sealed)",
    "blurb": "Curated trial sizes to discover your new favorites.",
    "bestseller": false,
    "description": "Eminence Organic Wild Plum Eye Cream in a lot of 6 sample cards — 2 ml each, 12 ml total. Iron-rich wild plum re-energizes and brightens the delicate eye area in this ophthalmologist-recommended cream. It deeply hydrates and comforts, visibly reduces signs of aging, firms and smooths skin texture, soothes the appearance of irritation, and leaves the eye area looking radiant and revitalized. Suitable for all skin types, including those concerned with dark circles. Authentic Eminence professional sample cards, new and sealed, stored in a temperature-controlled smoke-free environment."
  }
];

export const categories: { name: Category; subs: string[] }[] = (() => {
  const map = new Map<string, Set<string>>();
  for (const p of products) {
    if (!map.has(p.category)) map.set(p.category, new Set());
    map.get(p.category)!.add(p.sub);
  }
  const order: Category[] = ["Makeup", "Skincare", "Fragrance"];
  return order.filter(c => map.has(c)).map(c => ({ name: c, subs: [...map.get(c)!].sort() }));
})();

export const brands = [...new Set(products.map(p => p.brand))].sort();

export function getProduct(id: string) {
  return products.find(p => p.id === id);
}

export function relatedTo(p: Product, n = 4) {
  return products.filter(x => x.id !== p.id && x.sub === p.sub)
    .concat(products.filter(x => x.id !== p.id && x.category === p.category && x.sub !== p.sub))
    .slice(0, n);
}
